export const randomWords = [
    "apple", "banana", "orange", "grape", "kiwi",
    "house", "building", "street", "garden", "window",
    "computer", "keyboard", "mouse", "monitor", "software",
    "ocean", "mountain", "river", "forest", "desert",
    "bicycle", "car", "train", "airplane", "boat",
    "elephant", "giraffe", "tiger", "lion", "zebra",
    "happiness", "freedom", "courage", "kindness", "patience",
    "library", "school", "hospital", "station", "museum",
    "chocolate", "vanilla", "strawberry", "blueberry", "lemon", "sugar",
    "music", "dance", "art", "theater", "poetry",
    "friendship", "family", "community", "teamwork", "support",
    "technology", "innovation", "science", "research", "discovery",
    "nature", "environment", "wildlife", "conservation", "sustainability",
    "adventure", "exploration", "journey", "travel", "discovery",
    "health", "wellness", "fitness", "nutrition", "exercise",
    "imagination", "creativity", "inspiration", "dream", "vision",
    "language", "communication", "expression", "dialogue", "conversation",
    "history", "culture", "tradition", "heritage", "legacy",
    "sports", "competition", "victory", "team", "athlete",
    "food", "cuisine", "recipe", "flavor", "taste",
    "fashion", "style", "design", "trend", "accessory",
    "photography", "cinema", "film", "director", "actor",
    "literature", "novel", "poem", "story", "essay",
    "education", "learning", "knowledge", "wisdom", "skill",
    "finance", "economy", "investment", "savings", "budget",
    "politics", "government", "democracy", "election", "policy",
    "philosophy", "ethics", "morality", "belief", "values", "teemo", 
    "yasuo", "automata", "cyberpunk", "neural", "quantum"
];